### PR TITLE
issue_2279 fixed

### PR DESCRIPTION
**Pull request by PrakashDurlabhji**

### CODE REVIEW

**Comment by PrakashDurlabhji** [comment]
@maxceem sure will implement immediately.

**Comment by PrakashDurlabhji** [comment]
@maxceem icon has been reused and filled , please prvide feedback if any

**Comment by maxceem** [comment]
@PrakashDurlabhji please let me know your TopCoder handle, so I can process a payment for you for closed tickets during Bug Bash https://github.com/appirio-tech/connect-app/issues?q=is%3Aissue+is%3Aclosed+label%3ACF-12+assignee%3APrakashDurlabhji

Thanks.

**Comment by PrakashDurlabhji** [comment]
@maxceem topcoder handle is pkdurlabhji

**Comment by maxceem** [comment]
Hi @PrakashDurlabhji 

Please accept this Topcoder Terms https://www.topcoder.com/challenges/terms/detail/21303 so I can process a payment for you.

**Comment by PrakashDurlabhji** [comment]
@maxceem i clicked on above link.i can see complete agreement but unable to see any buttons through which i can accept. its just simple display page. what to do? how to accept?

**Comment by PrakashDurlabhji** [comment]
@maxceem @RishiRajSahu can anyone please help , as still going to above link, no submit button is present. then how will i accept ?

**Comment by PrakashDurlabhji** [comment]
@maxceem @RishiRajSahu request you to help me in this asap, because i am in bad need of money, as it takes 1 month for withdrawal, hence even 1 single day delay hurts a lot in my current situation. thanks.waiting for your comment.

**Comment by maxceem** [comment]
@PrakashDurlabhji I'm looking into this. Please, contact me in slack via **maxceem** so we can quickly try a few ways to solve it asap.

**Comment by maxceem** [comment]
@PrakashDurlabhji as a possible solution, please register to any public challenge, for example, https://www.topcoder.com/challenges/30071585. During registration, you will be asked to sign the required terms. After that, you can unregister from the challenge.
Let me know if it works for you and you signed the terms. After that, I'll process the payment immediately.

**Comment by PrakashDurlabhji** [comment]
@maxceem it worked. i guess its accepted.can you please cross verify?

**Comment by maxceem** [comment]
@PrakashDurlabhji yes, it works! I've proceeded the payment and you have to see during 24 hours. If not, please let me know.
Sorry for making you awaiting the payment. 
BTW to avoid such issues in the future, it would be better if you submit the text file to the Bug Bash challenge (like most pepople [did](https://www.topcoder.com/challenges/30070926?tab=details)), so you will get a payment together with everybody and terms acceptance will be handled properly.

**Pull request merged**
