### PR TITLE
#3513  Update Internal Catalog Display

### PR DESCRIPTION
**Pull request by yoution**

### CODE REVIEW

**Comment by yoution** [comment]
@maxceem  I try another method, I add `transform: translateZ(0);`. if I remove `scale`, the issue still exist. please review

**Comment by maxceem** [comment]
@yoution I can still reproduce the issue even with `transform: translateZ(0)`:

image

**Comment by yoution** [comment]
so just remove `scale` ?

**Comment by yoution** [comment]
@maxceem  please review again, remove `scale` and add 'float:right' may perfect

**Comment by maxceem** [comment]
> so just remove scale ?

Looks like removing scale doesn't help.

> @maxceem please review again, remove scale and add 'float:right' may perfect

thanks, I will check it out tomorrow

**Pull request merged**
