### PR TITLE
Feature/issue 2607 notifications transitions

### PR DESCRIPTION
**Pull request by maxceem**
This PR contains the solution for the issue #2607 

So far we keep it in a separate branch, as it's better to merge it together with https://github.com/appirio-tech/connect-app/issues/2649

Also, for now, it's against `cf13` branch, but if `cf13` is merged to `dev` we can change this PR to be merged directly to `dev` than.

FYI @RishiRajSahu

### CODE REVIEW

**Comment by RishiRajSahu** [comment]
@maxceem update the branch to `dev` instead of `cf13`

**Comment by maxceem** [comment]
@RishiRajSahu Yes, I'd prefer to accomplish #2649 before merging this one. I've created this PR as a reminder, so we don't forget about it.

**Comment by maxceem** [comment]
@RishiRajSahu as during CF14 we've implemented https://github.com/appirio-tech/connect-app/issues/2649 we can merge this PR.

I've resolved conflict and this PR can be merged to `cf14` branch.

**Comment by maxceem** [comment]
@vikasrohit this PR can be also merged, as CF14 contains fix for blocking issue. As CF14 is merged, now this also can be merged.

Note, this PR is against `cf14` branch.

**Comment by vikasrohit** [comment]
Thanks @maxceem

**Comment by vikasrohit** [comment]
@maxceem I just noticed that this PR was against CF14 branch which I have already merged into dev. So, would it be easy now to create and merge a new PR from this branch directly to the dev branch?

**Comment by maxceem** [comment]
@vikasrohit second PR https://github.com/appirio-tech/connect-app/pull/2797

**Pull request merged**
