### PR TITLE
fix for mil 53 #2040

### PR DESCRIPTION
**Pull request by sumitdaga**
@RishiRajSahu @gondzo

### CODE REVIEW

**Comment by gondzo** [comment]
@sumitdaga a few console errors when viewing in mobile
Warning: Failed prop type: The prop `title` is marked as required in `FeedMobile`, but its value is `undefined`.
Warning: Failed prop type: The prop `date` is marked as required in `FeedMobile`, but its value is `undefined`
Warning: Failed prop type: The prop `allowComments` is marked as required in `FeedMobile`, but its value is `undefined`.

sample project https://connect.topcoder-dev.com/projects/6375/plan

**Comment by gondzo** [comment]
Also, please pay attention to code linting and fix all errors before submitting a PR

**Comment by sumitdaga** [comment]
@gondzo  
there are no lint errors at least in this PR ...are there lint errors in any other PR?
i will take a look at the console errors

**Comment by gondzo** [comment]
no lint errors here, there was one in previous PR's, I've fixed it already.
you're right about these errors being from existing code. I'll create a new issues to track them

**Pull request merged**
