### PR TITLE
Fix for issue #1442

### PR DESCRIPTION
**Pull request by kevinkid**

### CODE REVIEW

**Comment by kevinkid** [comment]
Can i open a new pr on the dev branch? Used bugBash06 as the base.

**Comment by gondzo** [comment]
@kevinkid can you resolve conflicts for this one and remove `background:url` code instead of commenting it out.
there are a LOT of new icons with same boilerplate code. can we refactor that into helper function that returns the component based on icon path? or just remove them entirely and use babel plugin instead?

**Comment by kevinkid** [comment]
Okey @gondzo i will fix them in the next commit. I took the community-app approach because of performance during rapid state change on components eg. `ProjectToolBar` . Returning components based on icon path breaks consistency across the community-app but its a better approach to keeping consistency across all topcoder svg icons. We could add the icons to `appirio-tech-react-components/icons` component?  It would require a huge refactor on both connect-app and the appirio-tech-react-components repo but i will only make changes to icons that only affect the connect-app.

**Comment by gondzo** [comment]
let's not move the icons to react-components repo in this PR and take this step by step - just make sure to replace all occurrences of svgs used as img to babel-plugin-inline-react-svg approach

**Comment by vic-topcoder** [comment]
@kevinkid - do not remove `react-hot-loader` from `config/webpack/development.js` - this plugin make sure that all changes in local environment are precompiled and updates the front-end automatically

@vikasrohit - please confirm if I'm right

**Comment by vic-topcoder** [comment]
Once the PR is fixed I'll be able to test it/review better on my local environment.

**Comment by vikasrohit** [comment]
Yes, we should not get rid of `react-hot-loader`, it is needed for better dev env on local machines.

**Comment by kevinkid** [comment]
Sure @vic-topcoder and @vikasrohit , al be sure to keep things cleaner next time.

**Comment by vic-topcoder** [comment]
I left my comments at #1442 - please follow the correct way of including .SVG in all components. This refactor doesn't follow the standard implementation.

**Comment by vic-topcoder** [comment]
@kevinkid - left you several small bugs to fix in #1442. Once those are completed, we're ready to roll

**Comment by vic-topcoder** [comment]
@gondzo please review & merge. Spotted some small things and fixed them. Latest DEV is merged into the branch.

**Pull request merged**
