### PR TITLE
Update to v5 notifications api

### PR DESCRIPTION
**Pull request by gondzo**

### CODE REVIEW

**Comment by vikasrohit** [comment]
I thought, `limit` is the standard parameter for setting the page limit.

**Comment by gondzo** [comment]
v5 standard uses `per_page` and `page`

**Comment by gondzo** [comment]
here is the v5 standard document for reference (I'm not sure if it's hosted somewhere??)

[CORE-v5APIStandards-040518-2128.pdf](https://github.com/appirio-tech/connect-app/files/3201027/CORE-v5APIStandards-040518-2128.pdf)

**Comment by sachin-maheshwari** [comment]
@gondzo how we are using next pages in connect for list-notifications ? changes are required there too ?

**Comment by gondzo** [comment]
We aren't using it yet - we're just fetching a fixed number of notifications. That might even be ok since we always want to fetch all unread notifications, there is no pagination support

**Comment by vikasrohit** [comment]
Merging to dev as now tc-notifications is deployed to production with v5 changes and it is still backward compatible

**Pull request merged**
