### PR TITLE
Project Defaults, part 2

### PR DESCRIPTION
**Pull request by CDharmateja**
- Refactor NDAField implementation #4273 
- Add Groups Field https://github.com/appirio-tech/connect-app/issues/4270

### CODE REVIEW

**Review by maxceem — CHANGES_REQUESTED** [review]
Thank you for the timely update @CDharmateja. There are some improvements I'd like to make.

1. Once we save the form, the "Save" button never gets enabled again, see demo video https://monosnap.com/file/fPtLTnJcbqCt0kzGLpz8FGe9NToRGS

2. Can we, please, add prop definitions for the NDAField, like this https://github.com/appirio-tech/connect-app/blob/9cb0ed8e9dbf09aa4fab6cb25e11b6525ff6156f/src/projects/detail/components/AddonOptions/AddonOptions.jsx#L117-L125

3. Looks like `this.handleChange` is called twice
     image

4. Sorry, that I was not clear there. But can we keep 
   ```<SpecQuestionList>
              <Accordion
                title="Enforce Topcoder NDA"
                type="radio-group"
                options={opts}
              >
                <SpecQuestionList.Item>
     ```
     outside `NDAField` so we can use `NDAField` wrapper in the accordion, or if we don't need it, we can use it without an accordion.

**Comment by CDharmateja** [comment]
@maxceem  For 4th one I am having issues completing. Accordion is showing value 'Yes' or 'No' from its child formsy field. If NDAField is child component instead of RadioGroup, then the value passed to NDAField is used by Accordion instead of value of RadioGroup.

**Comment by maxceem** [comment]
Thanks, @CDharmateja the form works great now.

> For 4th one I am having issues completing. Accordion is showing value 'Yes' or 'No' from its child formsy field. If NDAField is child component instead of RadioGroup, then the value passed to NDAField is used by Accordion instead of value of RadioGroup.

Got it. Let's then remove Accordion completely for this form, as it makes everything harder. Please, remove `SpecQuestionList`, `Accordion` and `SpecQuestionList.Item` from `NDAField` and from `EditProjectDefaultForm`

image

and just add "label" for `RadioGroup` with value `Enforce Topcoder NDA`.

It would look like this, which is fine:

image


Also, I've noticed that there is a lint error. Please, fix them before I can merge it (don't disable lint rules).

image

**Review by maxceem — CHANGES_REQUESTED** [review]
Thank you @CDharmateja. Works almost perfectly. A few notes:

1. When I add or remove a group in the group select, there is API request is sent for each individual group, even though we already know the group name from the suggestions. Can we avoid it? As I understand we only need to request individual groups on page load to show their names. But when we edit them, we already know group names from the suggestions and don't have to make additional requests. See video https://monosnap.com/file/jozUeiuqy7WIdcjDBRe9OXFnHdNpy0

2. The label for the Groups Field should be "Intended Work Groups" instead of "Groups Field"

3. When showing label for NDAField you are using `<fieldset>` with `<legend>`, while for showing label for Group you just use `<div className={styles.container}>` with `<div className={styles.fieldName}>`. Is there any need in making it different ways? Or we can follow the same way in both cases?

**Comment by CDharmateja** [comment]
For 3, I used `fieldset` and `legend` for radio group since they have semantic meaning make more sense from accessibility point of view.

**Review by maxceem — APPROVED** [review]
> For 3, I used fieldset and legend for radio group since they have semantic meaning make more sense from accessibility point of view.

Makes sense.

Thank you @CDharmateja for taking care of all the feedback. Works perfectly now.

**Pull request merged**
