### PR TITLE
fix for issue #2934

### PR DESCRIPTION
**Pull request by gurmeetb**

### CODE REVIEW

**Comment by gurmeetb** [comment]
@maxceem are we sure we want this change, I revisited the details and it was expected to leave it that way, Refer the snapshot attached in final change details from you -

**Comment by maxceem** [comment]
@gurmeetb yes, we should make this change. This screenshot just shows the button which we have to take care about as we don't have a new design for this.

This button should work taking into account the new order and should be shown on the place where we "hide" old comments. In reverse order it's bottom.

**Comment by gurmeetb** [comment]
@maxceem no worries, updated MR with the change requested.

**Comment by maxceem** [comment]
Tested and works good.

**Pull request merged**
