### PR TITLE
fix for issue #3630

### PR DESCRIPTION
**Pull request by tcchhabra**

### CODE REVIEW

**Comment by tcchhabra** [comment]
@maxceem Welcome back alignment is not possible to keep same, because of the way the wizard is implemented. For that, we need to re-write impl class, which don't justify the prize here. We will need to bump prize to ~$50 for the same. It is not one button issue, it has whole wizard implementation issue, I guess the ticket was prize considering it is only height change for close button.

**Comment by maxceem** [comment]
Ok, @tcchhabra. We can bump the prize to $50 for this.

The expected result: close button goes up on this screen 
image

But everything else stays as it is. So, please, try not to make too big update if possible.

Also, please, get the latest changes from `cf21` branch as we fixed some issue related to these pages https://github.com/appirio-tech/connect-app/issues/3673.

**Comment by tcchhabra** [comment]
@maxceem taking some time but will try to wrap asap. Trying some tweaks with css and components to see if it could address all scenarios.

**Comment by tcchhabra** [comment]
@maxceem agree bumping the prize to $50 didn't made sense here, but to research and invest time to fix with minimal changes, see if we can maintain it at $30 to compensate for time.

**Comment by maxceem** [comment]
Ok, makes sense, will update to $30. Thanks.

**Pull request merged**
