### PR TITLE
add timezone input in profile settings page

### PR DESCRIPTION
**Pull request by vigneshTheDev**
Fix issue: https://github.com/appirio-tech/connect-app/issues/3359

### CODE REVIEW

**Comment by maxceem** [comment]
@RishiRajSahu I've noticed that in this PR apart from adding the timezone field some other change has been done. I'm not sure if they were required by some task or no:

- **Business phone** field is not required anymore, though it was required before.

**Comment by RishiRajSahu** [comment]
@vigneshTheDev could you address @maxceem comments here ?

**Comment by vigneshTheDev** [comment]
Hi @maxceem, sorry, it looks like a mistake. 
We had a scenario where some users 
* don't have values for required fields like company name and business phone. 
* and, the field is disabled due to the role based restrictions (https://github.com/appirio-tech/connect-app/issues/3277). 

In such case, the user will not be able to submit the profile settings form (because, the field is mandatory but it's empty and disabled. Related: https://github.com/appirio-tech/connect-app/issues/3277#issuecomment-534878815)

To handle this, I removed mandatory requirement from those fields. But later, we decided to make them mandatory again as the above mentioned issue can be addressed through customer support request. So, I reverted the company name field in this commit (https://github.com/appirio-tech/connect-app/pull/3365/commits/56b29cb4158d2c6fdb11c344d688379ee00f4536 - which is part of this pull request). I missed to revert mandatory requirement for business phone. Shall I fix it and raise a PR now?

**Comment by maxceem** [comment]
Thanks for the details @vigneshTheDev.

Yes, please, revert the unnecessary changes.

**Comment by maxceem** [comment]
Hey @vigneshTheDev, please, let me know when there is PR with reverted changes that are not necessary.
Thanks.

**Comment by vigneshTheDev** [comment]
Hi @maxceem, I've raised the PR here: https://github.com/appirio-tech/connect-app/pull/3416

**Pull request merged**
