### PR TITLE
adding temporary condition to avoid old notifications missing

### PR DESCRIPTION
**Pull request by sachin-maheshwari**
…eploying topic name change.

### CODE REVIEW

**Comment by vikasrohit** [comment]
Thanks @maxceem for the detailed review.

**Comment by sachin-maheshwari** [comment]
@maxceem FYI, the error you shared are coming before merging as well.

**Comment by maxceem** [comment]
Right @sachin-maheshwari. We have warnings to show that some notifications have types which we don't know how to process in Connect. After the notification types have been renamed in configs but not in DB we have many warnings. Because types in configs were updated, but for existent notifications in DB we have old types.

After the fix in this PR, most of warnings disappear because after this fix by new logic we already can find rules for notifications from the DB, but they are not correct.

So I've added new warnings in the screenshot above. They show which notifications rules we associate to which notifications types. So it can be seen, that we associate notification rules with type which don't match notification types.

**Comment by vikasrohit** [comment]
Agreed with @maxceem Reverting the PR.

**Pull request merged**
