### PR TITLE
fixes for #1696

### PR DESCRIPTION
**Pull request by veshu**
https://www.topcoder.com/challenges/30062936

### CODE REVIEW

**Comment by veshu** [comment]
@gondzo Can you please check the merge request?

**Comment by gondzo** [comment]
@veshu - just two minor issues
on project details there is some overlap
image
and some overlap on new project > chatbot
image

**Comment by veshu** [comment]
@gondzo this are not related to current scope, I will fix this. But since my submission is public now, are you accepting current fix for the scope, I will submit this issues later (in few hour)?

**Comment by gondzo** [comment]
they are in scope, check out the last two screenshots in the issue description. 
you're fine for the F2F :)

**Comment by kapilgorve** [comment]
@gondzo  If this challenge is F2F , how is the submission acceptable when listed issue is not fixed?  I

**Pull request merged**
