### PR TITLE
fix #1529 #1721: Detect if a notification has been seen vs. new notifications

### LINKED ISSUE #1529: [$600] Detect if a notification has been seen vs. new notifications
### Expected behavior
When the system sends out new notifications that I haven't see, I want the bell icon to have a red badge and the new notifications the have blue left border to indicate I haven't seen them.

The red badge would disappear once I open the drop-down menu.

The blue border would disappear once I click on the notification or visit the target location.

### Actual behavior
This doesn't exist currently

### LINKED ISSUE #1721: [$40] Red dot on the bell icon should be removed when there is no new notifications
_From @bikakk on February 18, 2018 15:9_

### Reported URL ###
https://connect.topcoder-dev.com/projects/2608

### Reproduction Steps ###
1. Open https://connect.topcoder-dev.com 
2. Login as pshah_customer
3. Trigger a notification for any of the project and observe the red dot on the bell icon for the indication of new notification triggered
4. Click on View all notification and make note of the count of all notifications
5. close the notifications 
6. Observe the Bell icon

### Expected Result ###

As per doc: https://docs.google.com/document/d/1OBUhMGUtqU-Eqpufaom_eAKDbLiR8mq6syb-PSavXDI/edit
If there is no new notification then white bell icon should display (Old notifications (white bell icon)

### Actual  Result ###

Red dot on the bell icon should be removed when there is no new notifications.
Here as per go to the notifications page and observed there are only 11 notifications displayed. Now close the notification window and observe still the red dot is not removed even there is no new notification triggered.

### Screenshots ###

[Red dot.docx](https://github.com/topcoderinc/connect-test-cycle-1/files/1734818/Red.dot.docx)

https://youtu.be/T-tw62ll7uc

### Issue Information ###

Frequency: Always

Device: Laptop

OS: Windows 7 64 bit

Browser: Chrome 64.0

_Copied from original issue: topcoderinc/connect-test-cycle-1#241_

### PR DESCRIPTION
**Pull request by zjuasmn**
fix #1529, fix #1721

### CODE REVIEW

**Comment by kevinkid** [comment]
The solution works well on that browser tabs session but lost across devices. Please confirm @gondzo

**Comment by zjuasmn** [comment]
@kevinkid works across devices requires server-side support, which repo and branch is the server code?

**Comment by kevinkid** [comment]
Use the https://github.com/topcoder-platform/tc-message-service repository.

**Comment by kevinkid** [comment]
@zjuasmn  Please assign me this issue.

**Comment by gondzo** [comment]
@kevinkid that's not the correct repository. @zjuasmn is still working on this one.
@zjuasmn the idea here was to have the seen status persisted to the database (hence the higher prize). The backend for this one is https://github.com/topcoder-platform/tc-notifications
Changes to the backend:
* add seen column to db
* add endpoint that updates seen status
* update get notifications endpoint to return seen status

Changes to the frontend:
* use the seen status to display the blue border
* update seen status using the new api endpoint

Let me know if you need more details here

**Comment by zjuasmn** [comment]
@gondzo I am working on backend-code of tc-notifications but cannot setup local  tc-notifications correctly by following the README. The cause is that `authSecret` on `connect.topcoder-dev.com` is not `secret` as it said in the README so I cannot auth user request from it. What is the `authSecret` of `connect.topcoder-dev.com`?

**Comment by gondzo** [comment]
you can disable token verification in tc-noptifications by editing package.json and instead of "tc-core-library-js": "appirio-tech/tc-core-library-js.git#v2.2", use "tc-core-library-js": "gondzo/tc-core-library-js.git#dev",

**Comment by zjuasmn** [comment]
server code PR submitted: https://github.com/topcoder-platform/tc-notifications/pull/20

**Pull request merged**
