### PR TITLE
changes in notification service endpoint and base url.

### PR DESCRIPTION
**Pull request by sachin-maheshwari**

### CODE REVIEW

**Comment by sachin-maheshwari** [comment]
@vikasrohit  as discussed please check this PR, I'll merge this once "tc-notifications" changes will be ready.

**Comment by vikasrohit** [comment]
LGTM 👍

**Comment by vikasrohit** [comment]
@gondzo Please review once.

**Comment by gondzo** [comment]
looks good.

**Comment by sachin-maheshwari** [comment]
@vikasrohit @gondzo  thanks guys. Please review again..did some changes again in list all notification endpoint, added 'list' prefix to support 'tyk'. Also removed context-path ('notifications') from corresponding individual endpoints.

**Pull request merged**
