### PR TITLE
Fix issue #4341: show the Invite Copilot button

### PR DESCRIPTION
**Pull request by diwosuwanto**
Show the Invite Copilot button (in the Manage copilots popup) for the admins #4341

### CODE REVIEW

**Comment by vikasrohit** [comment]
@diwosuwanto @mirzailhami I think the requirement says `Should not see the "Invite Copilot" capability at the bottom of the pop-up` that means, we do NOT need to show the Invite Copilot feature for the Manager only users (users who are manager but are also admins would continue to see this feature).

**Comment by vikasrohit** [comment]
To be 100% clear, we need to hide `Invite more copilots` section completely for every one except the admins.

**Comment by diwosuwanto** [comment]
@vikasrohit so we need to show invite more copilots only for this admin role? is it right?
image

**Comment by vikasrohit** [comment]
Yes

**Comment by diwosuwanto** [comment]
> > Show the Invite Copilot button (in the Manage copilots popup) for the admins #4341
> > 
> 
> @diwosuwanto Which role are you using here?

@mirzailhami  I'm using role in REMOVE_COPILOTS permission in this commit [https://github.com/appirio-tech/connect-app/pull/4377/commits/24e50a2ffc9d2ede5b86dfdc8641e9bd3160111e](url)
image

**Comment by vikasrohit** [comment]
@diwosuwanto @mirzailhami we need to show the Invite More Copilots only for `topcoderRoles` and that should match what is there in screenshot attached by @diwosuwanto i.e. TOPCODER_ADMINS and Copilot manager. And please add new permission if does not exist yet for controlling this feature, avoid reusing `REMOVE_COPILOT` permission as this permission might have different roles.

**Comment by diwosuwanto** [comment]
@vikasrohit @mirzailhami  I already commit the latest update, invite more copilots section will be show only for this Topcoder Admin level roles.
image

Logged in as Manager:
Screenshot from 2021-05-07 13-59-50

Logged in as Admin:
Screenshot from 2021-05-07 13-59-57

Please check it sir, thank you.

**Comment by vikasrohit** [comment]
Screenshots looks good to me @diwosuwanto, however, please add `ROLE_CONNECT_COPILOT_MANAGER` role to the `topcoderRoles` list for the new permission. This role is specifically for Copilot Managers who are admins as well for this particular operation.

**Comment by diwosuwanto** [comment]
> Screenshots looks good to me @diwosuwanto, however, please add `ROLE_CONNECT_COPILOT_MANAGER` role to the `topcoderRoles` list for the new permission. This role is specifically for Copilot Managers who are admins as well for this particular operation.

If i add `ROLE_CONNECT_COPILOT_MANAGER` role to the `topcoderRoles`, i think i don't need to do pull request sir because the `Copilot Invitation Permissions` already setup in dev branch. Is it right?

https://github.com/appirio-tech/connect-app/blob/d38f65e237782820e5aa6757c8aeee6f3571cca2/src/config/permissions.js#L233-L243

https://github.com/appirio-tech/connect-app/blob/d38f65e237782820e5aa6757c8aeee6f3571cca2/src/components/TeamManagement/CopilotManagementDialog.js#L185-L211

**Comment by mirzailhami** [comment]
> If i add `ROLE_CONNECT_COPILOT_MANAGER` role to the `topcoderRoles`, i think i don't need to do pull request or commit new changes sir @vikasrohit, because the `Copilot Invitation Permissions` already setup in dev branch. Is it right?

@diwosuwanto You can commit change into you current `issue-4341` branch, no need to send PR since this PR not merged yet.

**Comment by vikasrohit** [comment]
I got it what you are saying @diwosuwanto and it seems you are right that permission is already there to allow only admin and copilot manager to view the invite more copilots section. Let me come back to you guys after discussing it with issue reporter.

**Comment by vikasrohit** [comment]
@mirzailhami Please don't merge the PR until confirmation.

**Comment by mirzailhami** [comment]
@vikasrohit Sure. The variable was already there, that was what confuse @diwosuwanto.

**Comment by vikasrohit** [comment]
@mirzailhami not only the variable is there, it seems the changes we described in the original issue are already there, we don't need any thing to change here except the first part of the requirements which is 
> Update 1
If there are no Copilots on a project, users in the Manager role should:
>
>Only see the "Request Copilot" button.
Not see the "Manage" button.

**Comment by diwosuwanto** [comment]
Manager role when no Copilot on the project **(Update 1)**:
image


Manager role when there is a Copilot on the project **(Update 2)**:
image
image


Admin role when no Copilot on the project:
image
image


Admin role when there is a Copilot on the project:
image
image

**Comment by mirzailhami** [comment]
Look goods to me for the update 1. Please confirm @vikasrohit, any issues left here?

**Comment by vikasrohit** [comment]
Seems good to me. Thanks. Lets wrap this one as we don't have to do Update 2 because it is already there.

**Pull request merged**
