### PR TITLE
issue_2484 fixed

### PR DESCRIPTION
**Pull request by rashmi73**

### CODE REVIEW

**Comment by maxceem** [comment]
@rashmi73 please, let me know if are able/willing to provide fixes for the PR.

**Comment by rashmi73** [comment]
@maxceem updating it within 30 minutes

**Comment by rashmi73** [comment]
@maxceem PR updated

**Comment by maxceem** [comment]
@rashmi73 please, let me know if you are willing/available to finish this issue.
Thanks.

**Comment by rashmi73** [comment]
@maxceem working on it,will complete this

**Comment by rashmi73** [comment]
@maxceem suddenly m not able to see the add button, UI changed. can u please give me link to such a project which has + button visible.I tried every way not able to see it.I need final fix and i will raise PR then with all changes as in your comment. also it was working well.

**Comment by rashmi73** [comment]
@maxceem changes done and working as expected.

**Comment by rashmi73** [comment]
@maxceem it is looking perfect in firefox already, but still adding that property.
and removin linting too.

**Comment by rashmi73** [comment]
@maxceem PR updated

**Comment by maxceem** [comment]
> @maxceem it is looking perfect in firefox already, but still adding that property.
@rashmi73 Thanks, probably depends on the system or browser window size/resolution.

**Pull request merged**
