### PR TITLE
Github issue #257 [Specification] - the same image for different types of files uploaded

### PR DESCRIPTION
**Pull request by vikasrohit**
-- Dynamically picked icon for the file type

fyi, @parthshah please let me know if you think it can be improved

### CODE REVIEW

**Comment by parthshah** [comment]
Are there any comparisons on which method of loading svgs is more performant? 
This fix is fine for now IMO.

**Comment by vikasrohit** [comment]
You mean comparison between loading svg directly as image and loading them as React component? If yes, I guess @vic-appirio has better idea over that.

**Comment by vic-appirio** [comment]
I think that we can save ourselves time and effort if we can just dump the appropriate .svg files and dynamically convert them to react components. After some research of different approaches out there, [svg-react-loader](https://github.com/jhamlet/svg-react-loader/blob/version-0.4.0/README.md) seems like the best candidate for our tasks:
- design can dump/update/maintain the appropriate .svg files
- developers can request the icons in a consistent way, just need to know the correct filename
- icon properties could be handled by react-css-modules via `styleName` dynamically, which will limit the need to parameterize the .svg properties (consistency through reuse of global icon css classes).

Detailed [article for this approach](https://diessi.ca/blog/svg-images-as-react-components-with-webpack/);
Another [work-around for .SVG icon systems](http://blog.goguardian.com/nerds/an-odyssey-to-find-a-sustainable-icon-system-with-svgs-in-react)

As per performance - I have no idea which approach will be the fastest. My goal would be to load only 1 SVG and modify it properties instead of switching multiple static .svg or .png images.

**Comment by fnisen** [comment]
cc @vikasrohit, @parthshah

**Comment by vikasrohit** [comment]
Create separate issue to track this https://github.com/appirio-tech/connect-app/issues/481

**Pull request merged**
