### PR TITLE
Fixed #1402 maintaining a flag for card view listing and refreshing...

### LINKED ISSUE #1402: Duplicate projects in "customer" project listing immediately after creating a project.
Once you navigate the "view all projects" immediately after creating a project, there would be duplicate projects in project cart view. Once you reload the page, projects listing will be OK.

Before adding new project :-
projectslistbefore

After adding new project :- 
projectslistingafter

### PR DESCRIPTION
**Pull request by sachin-maheshwari**
…ard-view after navigation back on project listing.
Issue - https://github.com/appirio-tech/connect-app/issues/1402

### CODE REVIEW

**Comment by vikasrohit** [comment]
@sachin-maheshwari Can you please check your changes with [changes](https://github.com/appirio-tech/connect-app/blob/bugBash05/src/projects/actions/loadProjects.js) made in bug bash 05? It seems there we got same file altered and I think it would affect the issue in discussion. May be it got fixed with those changes? If yes, we can ignore this PR otherwise you might have to update the PR after we get bugBash05 merged into dev.

**Comment by sachin-maheshwari** [comment]
@vikasrohit as checked in BugBash05 branch, except one scenario, new project missing in project listing immediately after adding it, all others scenarios are working fine.

**Comment by vikasrohit** [comment]
So, we should close this PR and related issue and open up a new one for the failing scenario. It would be great if you can get that fixed as well. :)

**Comment by sachin-maheshwari** [comment]
As most of issues covered in bugBash05 milestone except which notice above so reported that on related issue https://github.com/appirio-tech/connect-app/issues/1373#issuecomment-351987934

**Comment by vikasrohit** [comment]
Thanks @sachin-maheshwari for the work and rechecking the issues with latest code as well.

**Pull request closed without merging**
