### PR TITLE
issue_2578 fixed

### PR DESCRIPTION
**Pull request by PrakashDurlabhji**

### CODE REVIEW

**Comment by maxceem** [comment]
@PrakashDurlabhji please note, that feedback has been provided 3 days ago, if a fix wouldn't be provided during next 24 hours, I'll have to unassign this issue from you.

**Comment by maxceem** [comment]
@PrakashDurlabhji there is already 3.5 days passed since feedback was provided, please fix the remaining issues or you will be unassigned.

**Comment by PrakashDurlabhji** [comment]
@maxceem working actively on it.PR immediately

**Comment by maxceem** [comment]
@PrakashDurlabhji thanks. Also, please fix lint error in other PR so I can merge it https://github.com/appirio-tech/connect-app/pull/2620#pullrequestreview-165445192. Thanks.

**Comment by PrakashDurlabhji** [comment]
@maxceem PR updated here

**Comment by maxceem** [comment]
Looks good to me

image

**Pull request merged**
