### PR TITLE
Update index.html to add Heap Analytics tracking

### PR DESCRIPTION
**Pull request by fnisen**
Will need to change the heap.load ID in prod

### CODE REVIEW

**Comment by vikasrohit** [comment]
@fnisen Updated the code to get the parameterized app id.

**Comment by fnisen** [comment]
Thank you @vikasrohit! Double-checked everything and it's looking good. Data is being collected in Dev. Can you please deploy to prod so we can start tracking?

**Comment by vikasrohit** [comment]
It would require all changes from the dev branch to be pushed to production. Are we good to go with production release with current set of changes in dev?

**Comment by fnisen** [comment]
@vikasrohit don't worry about this. We ended up pushing out the changes today b/c we needed to rush out the new terms page. I also found some issues with Vic's style changes, which he was able to fix. Thanks.

**Pull request merged**
