### PR TITLE
Issue 1538: Redesign and remove unnecessary project activity cards fr…

### PR DESCRIPTION
**Pull request by Colinh84**
…om Dashboard

#1538

### CODE REVIEW

**Comment by Colinh84** [comment]
Now also solves issue #1792

**Comment by gondzo** [comment]
@Colinh84 looks good, with two issues:
- clicking the close icon would hide only the shown notification (and mark it read) and display the next unread notification for that project. if there are no more unread notifications, the entire box is removed as is now.
- coder bot updates should be removed from the dashboard - filter them on api response
image

**Comment by Colinh84** [comment]
@gondzo I interpreted a comment by @vic-topcoder on the issue to mean that only the latest project notification should be shown and outdated earlier project messages should never be shown (marked as read along with latest when it is dismissed).. Are you saying that all project notifications should be displayed from latest to earliest as they are closed in the new box?

The comment by @vic-topcoder :
"Hide it permanently. By default we should show only the latest status update card if it wasn’t seen/dismissed yet."

**Comment by gondzo** [comment]
Yes, dismiss just the latest one, not all of them

**Comment by Colinh84** [comment]
@gondzo What about bundled notifications? Can we dismiss all notifications in a bundle at once (e.g. if specification is modified multiple times, those notifications are currently bundled into one message), or should each raw notification be displayed?

**Comment by gondzo** [comment]
we can dismiss all notifications in a bundle

**Comment by Colinh84** [comment]
@gondzo I've been trying to test my updates for this, but https://accounts.topcoder-dev.com is rejecting every test user login for the past hour, saying password is incorrect. I've tried all the logins I have: `pshah_customer`, `pshah_copilot`, `pshah_manager`, `pat_monahan`, `christina_uw`, `cp-superstar`, `Sky_`.. All give incorrect password error.

**Comment by gondzo** [comment]
pshah_manager/topcoder123 works for me at the moment.

**Comment by Colinh84** [comment]
@gondzo I'm still not able to login with any of the accounts, or even into a freshly created account.. I was still logged in as `pat_monahan` on one of my browsers and it worked as long as I didn't log out, so I was able to test my changes from there and injecting fake data for notifications since I can't create any new ones with another account.

**Pull request merged**
