### PR TITLE
[HOTFIX] [PROD] Post-release 2.4.15.2

### PR DESCRIPTION
**Pull request by maxceem**
This PR will contain the post-release fixes part 2. I think we can wait at least a day before merging it while collecting fixes. 

The list of fixes (**updated**):
- Fix for issue [P3: Update Invited Registered User Workflow](https://github.com/appirio-tech/connect-app/issues/3311). 
- Fix for issue [P3: Update Invited Unregistered 'Join Project' Workflow](https://github.com/appirio-tech/connect-app/issues/3310) which is not ready yet.
- Fix for issue [Handles are not cleared after successful invites](https://github.com/appirio-tech/connect-app/issues/3155)

### CODE REVIEW

**Comment by vikasrohit** [comment]
@maxceem if we are able to get pending fix by EOD, we can push this hotfix to prod today, otherwise I would like to wait for next week as tomorrow is Friday and I don't wan to cause any disruption to the services on weekends.

**Comment by maxceem** [comment]
> @maxceem if we are able to get pending fix by EOD.

I think we will hardly get it by the EOD. But if we do, I'll let you know asap.

> otherwise I would like to wait for next week as tomorrow is Friday and I don't wan to cause any disruption to the services on weekends.

Totally agree.

**Comment by vikasrohit** [comment]
@maxceem are we ready now for merging this PR to master?

**Comment by maxceem** [comment]
@vikasrohit not yet. I'm waiting for the final fixes for this PR https://github.com/appirio-tech/connect-app/pull/3356 which want to merge in this patch.

**Comment by maxceem** [comment]
@vikasrohit This PR is ready for deploying. It would be best if we deploy corresponding patch to DEV first for the staging testing.

**Comment by vikasrohit** [comment]
@maxceem as now we have this hotfix in dev, do you think it is stable to be released? I would not like to push it today as it is weekend now. So, I would schedule this patch release for Monday, if all things works as expected for us.

**Comment by maxceem** [comment]
@vikasrohit test on DEV. All works good for release.

**Pull request merged**
