### PR TITLE
Issue #1519 - Screen flicker in dropdown

### PR DESCRIPTION
**Pull request by maxceem**
Issue #1519 - Screen flicker in dropdown

### CODE REVIEW

**Comment by gondzo** [comment]
can we get rid of src/components/Dropdown/Dropdown.jsx now and in NotificationsDropdown.jsx use 
Dropdown from 'appirio-tech-react-components' ? https://github.com/appirio-tech/connect-app/commit/dd63928d95a2732bfca61a15d6c3c2cda00ecfdb#diff-7261d60c4a8f2da182ae77ab1a1827e1

**Comment by maxceem** [comment]
The reason why we use for Dropdown component from connect-app because it supports the next things:
- when we click **inside** dropdown nothing happens, so we can mark notifications as Read and so on, without closing dropdown immediately - other words this issue is fixed https://github.com/appirio-tech/connect-app/issues/1508
- when we click **outside** dropdown, its getting closed

The implementation of `appirio-tech-react-components` always closes opened dropdown no matter where we click.

Should be such behavior implemented in the Dropdown in 'appirio-tech-react-components' ?

**Comment by gondzo** [comment]
yes, please move the behavior to react components and remove the local
Dropdown component

**Comment by maxceem** [comment]
@gondzo just want to make sure that this is still valid to be implemented. Due to the discussion in the ticket [Remove dependency of old/obsolete technology](https://github.com/appirio-tech/connect-app/issues/1424#issuecomment-356092988) it sounds like it could be changed.

**Comment by gondzo** [comment]
yes, still valid. discussion in the referenced issue is a long term goal

**Comment by maxceem** [comment]
Added the second commit which removes `Dropdown` component from connect-app and utilizes updated `Dropdown` component from `appirio-tech-react-components` in [PR#280](https://github.com/appirio-tech/react-components/pull/280).

**Pull request merged**
