### PR TITLE
Update index.html

### PR DESCRIPTION
**Pull request by fnisen**
Adding Heap Analytics tracking script

### CODE REVIEW

**Comment by vikasrohit** [comment]
@fnisen This PR is against master branch. Is it intended?

**Comment by vikasrohit** [comment]
Further, how can we verify if it is working fine? I mean is there any dashboard/ui by Heap Analytics where we can see, before merging into master, that it is configured correctly.

**Comment by fnisen** [comment]
@vikasrohit - sorry, should have clarified in the PR. Yes, it was intentional because the data is separated per environment. And yes, you can check in the Heap Analytics app whether the data is flowing once the tracking code is added (I don't think there's a way to check beforehand). I've sent you an app invite by email.

**Comment by vikasrohit** [comment]
Okay, but merging a PR in master, would build and deploy to production.

**Comment by fnisen** [comment]
OK, what would you recommend?

**Pull request closed without merging**
