### PR TITLE
Issue 2896 fix

### PR DESCRIPTION
**Pull request by PrakashDurlabhji**

### CODE REVIEW

**Comment by maxceem** [comment]
@PrakashDurlabhji just in case would like to remind about this PR as the Bug Bash challenge in review phase now, which will be finished in 1.5 days.

**Comment by PrakashDurlabhji** [comment]
@maxceem which api  needs to be used?
removeProjectAttachment?

or

updateProjectAttachement with proper payload?

**Comment by maxceem** [comment]
@PrakashDurlabhji `removeProjectAttachment`, I think the issue is because you call with `idx` but I guess it should be called with attachmentId

**Comment by maxceem** [comment]
@PrakashDurlabhji there are also some conflicts with other changes has been done during this Bug Bash, please kindly resolve them before I can accept this PR.

**Comment by PrakashDurlabhji** [comment]
@maxceem is edit attachement working proper already? 

I dont think edit attachement is working as even it uses idx, 

Also there is no attachementId property in filelinks object, hence will implement same logic as links delete which splices the element at idx

**Comment by maxceem** [comment]
> is edit attachement working proper already?

it was broken and it has been fixed in another issue https://github.com/appirio-tech/connect-app/issues/2938

> I dont think edit attachement is working as even it uses idx,

right, it didn't work with idx

> Also there is no attachementId property in filelinks object, hence will implement same logic as links delete which splices the element at idx

plese, get the latest commits in the `cf16` branch, and check how the issue https://github.com/appirio-tech/connect-app/issues/2938 has been fixed in this PR https://github.com/appirio-tech/connect-app/pull/2942

I think in that issue attachementId has been added so you can reuse it in your submission.

**Comment by PrakashDurlabhji** [comment]
@maxceem MR updated with all points

**Pull request merged**
