### PR TITLE
issue_2492 Allow editing link for final deliverable

### PR DESCRIPTION
**Pull request by gets0ul**
Fix for issue #2492

### CODE REVIEW

**Comment by gets0ul** [comment]
Added new commit to only allow manager/copilot for editing final deliverable.

**Comment by gets0ul** [comment]
Thanks. I will submit another commit.

**Comment by gets0ul** [comment]
Done. Refactored it to be more readable.

**Comment by maxceem** [comment]
@gets0ul I've just realized that link is not actually updated when we edit it and save.

You can check this project http://local.topcoder-dev.com:3000/projects/7424/plan

- `Design Iteration (short)` phase is not finished yet, and we can edit delivery link successfully.
- `Visual Design` phase is already finished, we can click edit, change link and after save it, but it won't actually updated it would staty the same, see screencast https://monosnap.com/file/2tStkqohbL8llW5wf6bu66yOOllirF

**Comment by gets0ul** [comment]
It worked before, because I added that '/plan' part into the link.
I will check it .

**Comment by gets0ul** [comment]
The link won't change (it will revert to its previous value) if there were a final fix submitted.
When there were no submitted final fix, we can always edit the final delivery link.
http://local.topcoder-dev.com:3000/projects/7385/plan
  
When there were a submitted final fix, the link value always falls back to its previous metadata whether it is completed or not.
http://local.topcoder-dev.com:3000/projects/7424/plan

I will add new check that if a phase is already marked as completed, it will use new assigned link

**Comment by maxceem** [comment]
@gets0ul yep, we have to be able to edit link if it comes from final fixes or was added in deliverables.

After the last change link is not shown if we add it in final fixes
image

See project http://local.topcoder-dev.com:3000/projects/7385/plan, phase `Design Iteration (long)`.

**Comment by gets0ul** [comment]
Added new commit to correct the logic when completed delivery has previous final fix submitted.

**Comment by maxceem** [comment]
Great, it works good now!
Just fix lint error please, so I could merge it
```
/Users/maks/dev/topcoder/private/tc_connect_app/connect-app/src/projects/detail/components/timeline/milestones/MilestoneTypeDelivery/MilestoneTypeDelivery.jsx

║ Line     │ Column   │ Type     │ Message                                                │ Rule ID              ║
╟──────────┼──────────┼──────────┼────────────────────────────────────────────────────────┼──────────────────────╢
║ 209      │ 31       │ error    │ Extra semicolon.                                       │ semi                 ║
```

Thanks.

**Comment by gets0ul** [comment]
Fixed lint error.

**Pull request merged**
