### PR TITLE
Feature/v2 4 5 part2

### PR DESCRIPTION
**Pull request by vikasrohit**
fyi @RishiRajSahu @maxceem

### CODE REVIEW

**Comment by maxceem** [comment]
@vikasrohit  Tests are failing now. Making a fix at the moment...

**Comment by maxceem** [comment]
@vikasrohit tests are fixed.

**Comment by maxceem** [comment]
@vikasrohit In this PR there is one issue fixed which depends on the [PR 292](https://github.com/appirio-tech/react-components/pull/292) in react-components.

**Comment by vikasrohit** [comment]
Thanks @maxceem for the quick fix.

**Pull request merged**
