### PR TITLE
Issue #1437 - Page update reload suggestion

### PR DESCRIPTION
**Pull request by passimm**

### CODE REVIEW

**Comment by gondzo** [comment]
@passimm 
- The feed is reloaded even if I'm composing a new topic or comment - it should not do anything in that case
- if I scroll the page, the reload button is "displayed" but is not visible as it's on top of the feed. it should have absolute positioning in the feed container
- if there are new notifications when I load the page, it will still trigger a reload after the first timer

**Comment by passimm** [comment]
@gondzo . fixed above issues.

**Comment by passimm** [comment]
@gondzo . fixed above issues.

**Comment by passimm** [comment]
Hi @gondzo  any update about this?

**Pull request merged**
