### PR TITLE
issue_2272 fixed

### PR DESCRIPTION
**Pull request by Gauravseta**

### CODE REVIEW

**Comment by Gauravseta** [comment]
@maxceem working on actively raising PR within few hrs.

**Comment by maxceem** [comment]
@Gauravseta I see you've updated another PR, thanks! Please don't forget about this one too. Also, there is merging conflict now to fix.

**Comment by maxceem** [comment]
@Gauravseta I see you've updated another PR, please, don't forget to update this PR also, as Bug Bash challenge is almost finished.
Thanks.

**Comment by Gauravseta** [comment]
@maxceem working on it. PR within 15mins

**Comment by Gauravseta** [comment]
@maxceem kindly check the PR. its updated.

**Comment by maxceem** [comment]
@Gauravseta please, let me know if you are willing/available to finish this issue.
Thanks.

**Comment by Gauravseta** [comment]
@maxceem yes i am available and will finish it immediately.

**Comment by Gauravseta** [comment]
@maxceem npm run lint is not working at my end.hence proper care is taken for linting issue, regarding functionality and css, it should work perfectly now. i have kept header color black and white cross on right.

is that correct? or some other changes required?
for title i am displaying milestone name, is it ok too?
kindly provide feedback if something left, to my knowledge it is perfect PR now.

**Comment by maxceem** [comment]
@Gauravseta

1. It still doesn't fill the whole screen if there is less content than for the whole screen:
    image
    - I guess the only thing has to be done is to use the same color for the background.

2. Could you please make the header look same as for posts as this design was already confirmed, and we show such header for simmilar places:
    
   - gray color background should be same like the rest part of milestone form
   - text is aligned to the left
   - cross on the right
   - form separated from the header by a thin line color `$tc-gray-10`

3. There are still lint errors. It's strange that `npm run lint` doesn't work for you, could you please let me know what error you get when you run it? It is supposed to work for everybody.

    ```
     /Users/maks/dev/topcoder/projects/connect/connect-app/src/projects/detail/components/timeline/Milestone/Milestone.jsx

     ║ Line     │ Column   │ Type     │ Message                                                │ Rule ID              ║
     ║ 41       │ 69       │ error    │ Extra semicolon.                                       │ semi                 ║
     ║ 292      │ 1        │ error    │ Expected indentation of 20 spaces but found 22.        │ indent               
     ║
     ║ 293      │ 1        │ error    │ Expected indentation of 22 spaces but found 24.        │ indent               
     ║
     ║ 294      │ 1        │ error    │ Expected indentation of 24 spaces but found 26.        │ indent               
     ║
     ║ 295      │ 28       │ error    │ Empty components are self-closing                      │ react/self-closing-  
     ║
     ║          │          │          │                                                        │ comp                 ║
     ║ 298      │ 1        │ error    │ Expected indentation of 22 spaces but found 24.        │ indent               
     ║
     ║ 299      │ 1        │ error    │ Expected indentation of 20 spaces but found 22.        │ indent               
     ║
     ║ 300      │ 1        │ error    │ Expected indentation of 18 spaces but found 20.        │ indent               ║
    ```

**Comment by Gauravseta** [comment]
@maxceem updating you immediately here.want to finish this as soon as possible

**Comment by Gauravseta** [comment]
@maxceem is backend down? suddenly unable to see project list.
shall i create new project myself?

**Comment by Gauravseta** [comment]
suddenly this is issue in console.

**Comment by maxceem** [comment]
@Gauravseta it works for me. It could be that internet connection is slow, and you reach the request timeout. You may try putting here https://github.com/appirio-tech/connect-app/blob/dev/src/api/requestInterceptor.js#L28 `60000` - 60 seconds for the timeout or more. I think it will resolve the error you are facing.

**Comment by Gauravseta** [comment]
@maxceem even without it its done.for linting issues, i will fix it with npm run lint:fix, and make commit.

**Comment by Gauravseta** [comment]
@maxceem all linting resolved and header is as expected and it will take complete height of screen now.

**Comment by Gauravseta** [comment]
@maxceem screenshot for reference.

**Comment by Gauravseta** [comment]
@maxceem can you please review it

**Comment by RishiRajSahu** [comment]
@Gauravseta could you submit the required changes ?

**Comment by Gauravseta** [comment]
@RishiRajSahu @maxceem sorry for the delay. working on it. near to complete it and complete logic in my mind.implementing it. give me few hours

**Comment by RishiRajSahu** [comment]
@Gauravseta This issue is blocking us to conclude Community-fixes challenge. Please release the issue if its going to take time.

**Comment by Gauravseta** [comment]
@RishiRajSahu sorry. just give me half an hr sure. if i couldnt then il unassign myself sure. just few more mins

**Comment by RishiRajSahu** [comment]
@Gauravseta Okay.

**Comment by Gauravseta** [comment]
@rishirajsahu why suddenyl cred not workibg?

**Comment by Gauravseta** [comment]
@rishirajsahu are all projects removed from pshah_customer and pshah_manager?

**Comment by Gauravseta** [comment]
@rishirajsahu @maxceem PR updated.its working now

**Pull request merged**
