### PR TITLE
Issue #3424

### PR DESCRIPTION
**Pull request by romitgithub**
Added permissions to show member suggestions

### CODE REVIEW

**Comment by romitgithub** [comment]
Fixes issue https://github.com/appirio-tech/connect-app/issues/3424

**Comment by romitgithub** [comment]
@maxceem changes done. Please check once.

And for formatting, I use VSCode and the eslint declaration in the project. The editor provides an easy way to format the files on save.

**Comment by romitgithub** [comment]
@maxceem  Done.

**Comment by maxceem** [comment]
> And for formatting, I use VSCode and the eslint declaration in the project. The editor provides an easy way to format the files on save.

Thanks for letting me know. Strange that VSCode eslint formats the project differently from what happens if we run `npm run lint` command if they both take the config from the same file. I will have a look at this later.

**Pull request merged**
