### PR TITLE
Issue 3132  fix

### PR DESCRIPTION
**Pull request by rashmi73**

### CODE REVIEW

**Comment by rashmi73** [comment]
@maxceem I saw that, dont know why it is happening like this only in producttemplate, as flow is similar for everyone. checking backend tc-project-service

**Comment by rashmi73** [comment]
@maxceem till then I will look into this and try to fix for productTemplates

**Comment by maxceem** [comment]
@rashmi73 any luck with this one?

**Comment by maxceem** [comment]
@rashmi73 do you think you can complete this task?

**Comment by rashmi73** [comment]
@maxceem yes it is completed and working as per expectation now. kindly check

**Pull request merged**
