### PR TITLE
Issues #2567 fixed

### PR DESCRIPTION
**Pull request by jankyzhang**

### CODE REVIEW

**Comment by jankyzhang** [comment]
@maxceem  Sorry for the bug.
I check it right now.

**Comment by jankyzhang** [comment]
@maxceem ,
I have fixed it.
Please check.

**Comment by maxceem** [comment]
@jankyzhang looks like it still doesn't work when we click the bell, check screencast https://monosnap.com/file/Wmu8AoiRPmIwGFi36bt2hdjbZ0PrKh

**Comment by jankyzhang** [comment]
@maxceem 
It may due to the old commit of 'react-components' .
Please cancel the commit of 'react-components'  which I even submit.

About this issues,
Only the commit of connect-app will be ok.

https://monosnap.com/file/yFSonosNAmKrIBETUjmKnke8OxpPKp

**Pull request merged**
