### PR TITLE
fix #1993 Seems like project is not being removed from the local storage …

### LINKED ISSUE #1993: [$60] Seems like project is not being removed from the local storage after creation
### Expected behavior
Ideally, it should remove the project from the local storage once the new project is created.

### Actual behavior
Even after successful creation of a project, we can see the same project still present in the local storage.

### Steps to reproduce the problem
- Create a new project
- Click on new project button immediately after successful creation of the first project.
- Notice that you are represented with incomplete project screen which signifies that we still have the project data in local storage.

--

#### Environment
- OS: Any
- Browser (w/version): Any
- User role (client, copilot or manager): Any
- Account used: N/A

### PR DESCRIPTION
**Pull request by zjuasmn**
…after creation

Related to #1731.
When user navigate from project detail to create new project page, these two page refer to the same project object in redux store, So the current condition would not consider it successfully created.

The delay execution of `history.push` is to let user see notification after they creating project.

### CODE REVIEW

**Comment by zjuasmn** [comment]
also fix #2151

**Comment by gondzo** [comment]
@zjuasmn when clicking the create project button, this will show the loading indicator, then briefly show the new project wizard again and then finally the project details page (loading indicator and then the project page). 
What we need is just loading indicator and target page.

**Comment by zjuasmn** [comment]
@gondzo done.

**Comment by gondzo** [comment]
@zjuasmn looks better. there is some issue with alerts being shown without styling in between the transition, see https://www.screencast.com/t/bf65IcdC

Also, let's remove 
```
if (this.state.createdProject) {
+      return null
+    }
```
and set 
```
<EnhancedCreateView ...
processing={ this.state.creatingProject || this.state.createdProject}
```

**Comment by zjuasmn** [comment]
@gondzo I try trigger `Alert.success` in create view and found that the style is same with that in your video. The alert box style is customized in <https://github.com/appirio-tech/connect-app/blob/dev/src/styles/vendors/s-alert-default.scss>.

Shall I change the style to base on default style in `react-s-alert`?

**Comment by gondzo** [comment]
good catch. can you investigate & fix alerts as well?

**Comment by zjuasmn** [comment]
@gondzo Alert works now.
image

**Pull request merged**
