### PR TITLE
Screen number options in project specification

### LINKED ISSUE #638: Screen number options in project specification
### Expected behavior
The maximum number of screens in the project specification should be 10, not 7.

### Actual behavior
Maximum number of screens is 7

### Steps to reproduce the problem
Create a project and go to the project specification page

### Screenshot/screencast

image

--

#### Environment
- OS:all
- Browser (w/version):all
- User role (client, copilot or manager):all
- Account used: all

### PR DESCRIPTION
**Pull request by ThomasKranitsas**
Closes #638

### CODE REVIEW

**Comment by gondzo** [comment]
@ThomasKranitsas we also need to remove the "Skip this question" checkbox for this question

**Comment by ThomasKranitsas** [comment]
@gondzo don't close this PR.. I'll push another commit here

**Comment by gondzo** [comment]
ok, thanks

**Comment by ThomasKranitsas** [comment]
@gondzo I removed the **Skip question**.. You can now test it :)

**Pull request merged**
