### PR TITLE
Hotfix/post release 2.4.15.2

### PR DESCRIPTION
**Pull request by vikasrohit**
Dev version

### CODE REVIEW

**Comment by vikasrohit** [comment]
@maxceem PR has lint errors

**Comment by maxceem** [comment]
> @maxceem PR has lint errors

That's weird. I don't have lint errors locally.
I've refactored code to avoid the error reported by CircleCI.

**Comment by maxceem** [comment]
@vikasrohit lint error is fixed.

**Comment by vikasrohit** [comment]
@RishiRajSahu merging in dev for quick sanity testing before merging to master.

**Comment by RishiRajSahu** [comment]
@maxceem does this contains new invite flows for both registered/unregistered user ?

**Comment by maxceem** [comment]
@RishiRajSahu here is the list of fixes in this PR:
- Fix for issue [P3: Update Invited Registered User Workflow](https://github.com/appirio-tech/connect-app/issues/3311). 
- Fix for issue [P3: Update Invited Unregistered 'Join Project' Workflow](https://github.com/appirio-tech/connect-app/issues/3310) which is not ready yet.
- Fix for issue [Handles are not cleared after successful invites](https://github.com/appirio-tech/connect-app/issues/3155)

> does this contains new invite flows for both registered/unregistered user ?

It contains support for the invitation links for immediate accept/decline. We still have to update email templates https://github.com/appirio-tech/connect-app/issues/3311#issuecomment-539804510. But it's in another repo.

**Comment by RishiRajSahu** [comment]
@maxceem thanks, could you create a PR for the templates as well ?

**Comment by maxceem** [comment]
> @maxceem thanks, could you create a PR for the templates as well ?

It's not yet ready, I'm a little bit stuck with fixing the reindexing issue.

**Pull request merged**
