### PR TITLE
style talent picker component

### PR DESCRIPTION
**Pull request by vigneshTheDev**

### CODE REVIEW

**Comment by vigneshTheDev** [comment]
Hi @maxceem, Issue #1 is fixed.

For #2, are you trying to copy paste non numbers?

**Comment by maxceem** [comment]
@vigneshTheDev I'm trying to copy/paste numbers. 

Note, even if I try to `copy` from the field, it doesn't copy.

I think because I use key `command` and in the PR you are checking for `ctrl` (I think).

**Comment by vigneshTheDev** [comment]
@maxceem, yeah you're correct. Fixed it now. Can you please verify?

**Comment by maxceem** [comment]
@vigneshTheDev from the quick test it works great now. I would recheck everything the final time tomorrow morning.

**Pull request merged**
