### PR TITLE
Fix Issue #1196

### PR DESCRIPTION
**Pull request by maxceem**
Fix for issue #1196 

- webpack updated to v3.6.0 and webpack-dev-server to v2.9.1
- `extract-text-webpack-plugin` replaced with `extract-css-chunks-webpack-plugin` from the fork of birdofpreyru
Seeing that webpack-config project has been using as a kind of universal config, there was a lot of stuff which is not used by connect-app, so I removed it:
- removed support for `jade`-like formats as they are not used in in the project
- removed `--tc` argument from webpack command, haven't found any usage in config
- removed `--silent` param inside webpack config as haven't found any usage in config
- removed `--test` param inside webpack config as webpack was never called with this param
- removed `DedupePlugin`
- removed `__MOCK__` variable from `DefinePlugin` as it never appears in the project

- `npm run test` and `npm run test:watch` don't work as it was before

- there is one small issue after migration:
  When we run the project in dev mode with hot reloading and make first change, hot reloading works, but first time it triggers components remount, next reloads don't
  it could be connected with the fact that react-hot-loader doesn't fully support react-router@3,
  migration to react-router@4 probably can solve it

### CODE REVIEW

**Comment by gondzo** [comment]
@vic-topcoder @vikasrohit @mtwomey 
Looks like we need to update react-router from 3 to 4 to complete this migration to webpack 3 (otherwise hot reload doesn't work). IMO we shouldn't merge this until we have hot reload working properly. Any ideas ?

**Comment by mtwomey** [comment]
@gondzo Can we do a paid task to do the upgrade for react-router?

**Comment by gondzo** [comment]
Sure. Merging this one to test02 and I'll merge to dev once react-router is updated.

**Comment by kevinkid** [comment]
Al be happy to work on it as private task .

**Comment by gondzo** [comment]
It's assigned to a different member already.

**Comment by kevinkid** [comment]
cool thanks

**Pull request merged**
