### PR TITLE
issue_2518 Fix Jumbled/Incorrect Words Appearing in Projects

### PR DESCRIPTION
**Pull request by gets0ul**
Fix for issue #2518

### CODE REVIEW

**Comment by gets0ul** [comment]
Added fix for project list.

**Comment by vikasrohit** [comment]
@maxceem Just out of curiosity, could these changes cause the script injection in the platform?

**Comment by vikasrohit** [comment]
Also, there might be one more place where the same cause is causing the issue. It is in ref code, if you try adding `R&D` as ref code, it renders as `R&amp;D`. It might be a backend issue as well.

**Comment by maxceem** [comment]
@vikasrohit yeah, I've also was curious about that. I've checked all the places and think it's safe as we use this text inside
- react components which don't let us insert HTML
- values of input/textarea
- property of `React-Text-Truncate` which also inserts text using react components https://github.com/ShinyChang/React-Text-Truncate/blob/master/src/TextTruncate.js#L233

**Comment by maxceem** [comment]
> Also, there might be one more place where the same cause is causing the issue. It is in ref code, if you try adding R&D as ref code, it renders as R&amp;D

Oh, I've missed that, thanks. I've fixed it in this commit 85f18529dc84fe70ee348507577219a5df4272c0

> It might be a backend issue as well.

Yes, encoding is done by the backend, but I think it's a good thing for us, as it keeps us safe from injections.

**Comment by vikasrohit** [comment]
> Oh, I've missed that, thanks. I've fixed it in this commit 85f1852

Thanks @maxceem However, I am worried about ref code thing because if it is encoded in database, it is tricky and confusing to query projects by ref code in our reporting system because we are rendering `R&D` while in database it is `R&amp;D`. Is it possible, on front end, to keep it `R&D` at both places?

**Comment by maxceem** [comment]
@vikasrohit I think we cannot handle it frontside.

Even if I send API request using postman with & presented it would be returned from the backend as `&amp;`

So I think we have to fix it on backend.
Though we can check if backend encodes symbols before saving data, or before returning it. So there is small probability that data is stored original way and searching would work correctly.

Otherwise we can check if it's possible to disable encoding in the backend for one field REF only.

**Pull request merged**
