### PR TITLE
Issue 2401

### PR DESCRIPTION
**Pull request by vikasrohit**
Looks good to me.

Merging to test out in dev. fyi @RishiRajSahu

### CODE REVIEW

**Comment by vikasrohit** [comment]
@maxceem Seems like there are lint errors.

**Comment by maxceem** [comment]
@vikasrohit that's very strange. These errors happen either at my local machine or if fixed, happen on CI. probably some version mismatches, I'll check.

**Comment by vikasrohit** [comment]
@maxceem the difference between local and CI is that CI might be caching the old version of a dependency because of it `package-lock.json` based caching unless this file is updated. OR there might be case where the cache is bursted on CI because we have a change in `package-lock.json` file but it is not bursted at our local.

**Comment by maxceem** [comment]
Fixed.

**Comment by vikasrohit** [comment]
Thanks @maxceem, Merged in dev.

**Pull request merged**
