### PR TITLE
Issue 3210 fix

### PR DESCRIPTION
**Pull request by rashmi73**

### CODE REVIEW

**Comment by rashmi73** [comment]
@maxceem I will address all 4 points immediately,
but I am confused regarding pt 2.

1. whether pt 2 was requirement of this issue? or such error has been introduced due to mine code?
can you please give project number of it, it would be helpful for me.

2. Also regarding your pt 1, I have not touched manager functionality, so it shall function as it is.only admin check is added in code, can you also please provide project number for this so I can get it immediately?

**Comment by maxceem** [comment]
1. Regarding point 2. Before nobody can edit phases after they are completed. And now admins should be able to do it. So this was not implemented before, and it's a part of this task, see this comment pt 1 https://github.com/appirio-tech/connect-app/issues/3210#issuecomment-530738969

2. I tested with project 7442. So when I deploy locally with your PR http://local.topcoder-dev.com:3000/projects/7442/ I cannot edit any phase. But if I open current implementation by link https://connect.topcoder-dev.com/projects/7442 - I can edit not-completed phases.

**Comment by rashmi73** [comment]
@maxceem is backend down? because on all projects list, I suddenly get error screen with following error

Topcoder Connect Issue Report D’oh! Something went wrong Error: Request failed with status code 502 at createError (webpack-internal:///./node_modules/axios/lib/core/createError.js:15:15) at settle (webpack-internal:///./node_modules/axios/lib/core/settle.js:18:12) at XMLHttpRequest.handleLoad (webpack-internal:///./node_modules/axios/lib/adapters/xhr.js:75:7)


Actually project list is loaded and seen, then within 1 sec i get error screen

any issues?

**Comment by maxceem** [comment]
Yes @rashmi73. One of the backend services (Member Service) is down. But it's not critical and there is a patch in Connect App, so it works even without Member Service. 

So get the latest commits in `cf19` branch, and after you could load Project Listing page, only users data cannot be loaded, but it's not critical.

**Comment by maxceem** [comment]
@rashmi73 regarding 1pt. I think this issue is only in old `cf19` branch. You can try to fetch the latest commits in `cf19` and this issue suppose to go away.

**Comment by rashmi73** [comment]
**1. After update pshah_manager cannot edit not-completed phases. But Managers should be still able to edit not-completed phases as before. Changes are only for admin users.**

I am not able to observe such  behaviour as mentioned in your comment with before and after image for pshah_manager.

can you please confirm above behaviour again?

**Comment by maxceem** [comment]
@rashmi73 after the last update I cannot build project.
When I run `npm start` I get error:
```
Module build failed: Error: /Users/maks/dev/topcoder/projects/connect/connect-app/src/projects/detail/components/timeline/FormFieldDate/FormFieldDate.jsx: Cannot use styleName attribute for style name 'milestone-post' without importing at least one stylesheet.
```

image

**Comment by rashmi73** [comment]
@maxceem it was built perfectly on my machine. checking

**Comment by rashmi73** [comment]
@maxceem PR update it should work fine now

**Comment by maxceem** [comment]
@rashmi73 do you think you can update on this shortly? This issue has a priority.

**Comment by rashmi73** [comment]
@maxceem sorry for delay I will be able to complete it sometime

**Comment by maxceem** [comment]
Thanks for update @rashmi73. How much time do you need to complete this one?

**Comment by rashmi73** [comment]
@maxceem within an hour

**Comment by rashmi73** [comment]
@maxceem
1. can you please provide admin credentials?

2. Can you please provide project number on which you are exactly testing. because everything is working fine at my end hence lets target it step by step. I would paste screenshot for each so that it is verified.

**Comment by maxceem** [comment]
1. @rashmi73 I cannot provide the admin account. But this can be tested by making the next change in the Connect App, so the user behaves like admin:
    Add the next line of code:
    ```js
    currentUser.roles.push('administrator')
    ```
    After line `53` in this file https://github.com/appirio-tech/connect-app/blob/dev/src/actions/loadUser.js#L53 so it looks like this:

    image

2. I test with this project http://local.topcoder-dev.com:3000/projects/7442

**Comment by rashmi73** [comment]
@maxceem thanks. Pr is updated. Mostly all working Kindly provide feedback if any. waiting.

**Pull request merged**
