### PR TITLE
#1268 : Project sidebar visual updates

### PR DESCRIPTION
**Pull request by sachin-maheshwari**

### CODE REVIEW

**Comment by vic-topcoder** [comment]
I got a react-router error when installing clean and running. @sachin-maheshwari let's fix it so I can review before merging.

**Comment by mtwomey** [comment]
@sachin-maheshwari Confirmed on my end. This worked for me at first, but tried in incognito mode and it fails for me also with the above error message. (it probably worked at first, because of caches resources).

**Comment by sachin-maheshwari** [comment]
@vic-topcoder, @mtwomey, check now.

**Comment by vikasrohit** [comment]
@sachin-maheshwari Please create PR against feature/project-listing-updates instead of dev. Your PR is having partial changes for issues I am working on and it would cause conflicts when I would create PR against dev.

**Comment by sachin-maheshwari** [comment]
PR - https://github.com/appirio-tech/connect-app/pull/1293

**Pull request closed without merging**
