### PR TITLE
feat: don't reload phases after adding

### PR DESCRIPTION
**Pull request by maxceem**
This fix to avoid the issue with a delay of ES indexing after moving from RabbitMQ to Kafka in Project Service, see https://github.com/topcoder-platform/tc-project-service/issues/584#issuecomment-709286420.

### CODE REVIEW

**Comment by vikasrohit** [comment]
@maxceem how does it fixes the delay in indexing? It is still reloading the page which might get old data. Should we put explicitly delay of 5 seconds like member acceptance?

**Comment by maxceem** [comment]
@vikasrohit page should not be reloaded after this fix. Is it still reloading for you?

**Comment by vikasrohit** [comment]
Nopes, I didn't try, I just tried to interpret the code.

**Comment by maxceem** [comment]
I've removed the reference to the action `loadProjectDashboard` as it's not called to keep things clear.

**Comment by vikasrohit** [comment]
ok, so how the problem of delay is solved with this change?

**Comment by maxceem** [comment]
yes, as per my local testing.

**Comment by vikasrohit** [comment]
Okay, however, my concern is that what is solution that we implemented in this PR to resolve the delay issue? I am not seeing the 5 second delay added.

**Comment by maxceem** [comment]
Workflow before was:
- `POST /phases` - create a new phase on the server
- `GET /phases` - load all the phases from the server as we expected cascading updates
- redraw all the phases which we loaded from the server

Workflow now:
- `POST /phases` - create a new phase on the server
- just add a newly added phase client-side without reloaded all the phases

So we don't need a 5 seconds delay, because we don't reload the phases. And `POST /phases` endpoint returns newly created phase immediately.

**Comment by vikasrohit** [comment]
Gotcha!!

**Pull request merged**
