### PR TITLE
notification modal fix #1790

### LINKED ISSUE #1790: [$60] click on the notification message should dismiss the modal
_From @winterflame on February 19, 2018 9:39_

### Reported URL ###

*https://connect.topcoder-dev.com/projects/2652/specification*

### Reproduction Steps ###
1. login to https://connect.topcoder-dev.com/ using pshah_manager/topcoder123 
2. create a new project, then update the project (e.g. edit project details) so that some notifications are received
3. go to specification page: https://connect.topcoder-dev.com/projects/2652/specification
4. click the Bell icon, click on the notification message on the modal, observe

### Expected Result ###

*Click on the notification detail should dismiss the modal.*

### Actual Result ###

*See screencasts, if it is already on the current specification page, it won't dismiss the modal.*

### Screencasts ###
https://youtu.be/Z5sEDGXfFqE

### Issue Information ###

Frequency: *Always*

Device: *Mac Pro*

OS: *Mac OS 10.13.3*

Browser: *Firefox 58.0.2(64-bit)*

_Copied from original issue: topcoderinc/connect-test-cycle-1#306_

### PR DESCRIPTION
**Pull request by anonymousjaggu**
fix for modal close notification #1790

### CODE REVIEW

**Comment by gondzo** [comment]
this change breaks the notification dropdown - can't mark the notification as read, can't click mark all as read @anonymousjaggu

**Comment by gondzo** [comment]
@anonymousjaggu can you fix the above issues and update the PR

**Comment by anonymousjaggu** [comment]
sure I will fix this

**Comment by anonymousjaggu** [comment]
@gondzo I am getting this error while running the latest code
image

can you pleas verify this is issue in my side or the issue is in code

**Pull request closed without merging**
