### PR TITLE
bug #3273 Show Created By for files and links list in Assets Library

### PR DESCRIPTION
**Pull request by jankyzhang**

### CODE REVIEW

**Comment by maxceem** [comment]
@jankyzhang there is some issue with the Member Service. It's not connected with your PR, but I cannot test it properly. So I'm waiting for the member service to come back live.

**Comment by jankyzhang** [comment]
@maxceem 
Sorry for the delay reply.
I miss the E-mail notification.
I check it right now.

**Comment by jankyzhang** [comment]
@maxceem,  
I have fix two issues now.
Please check the code.

About the issue 2:
In the 'AssetsInfoContainer.jsx' . the 'props.projectMembers' is accroding of the state 'members.members' ,which get from the existent action 'loadMembers'.
If we use the action 'loadMembers' again for 'assetsMembers'.
The  'props.projectMembers' may be changed.
So I implement a new action to load information about user members at first.

**Comment by jankyzhang** [comment]
@maxceem ,
Thanks for the reply.
Now the Service is fail.
I will check and fix the issue today later.
screenshot-connect topcoder-dev com-2019 09 29-22_52_06

**Comment by jankyzhang** [comment]
@maxceem 
screenshot-local topcoder-dev com_3000-2019 09 30-01_09_35
Website try to get the user-info about '305384'.
However, just a blank content return. 
So the code request to the server again and again, due to the missUserId '305384'.

How we should do about this ?

**Comment by maxceem** [comment]
> Website try to get the user-info about '305384'.
> However, just a blank content return.
> So the code request to the server again and again, due to the missUserId '305384'.

> How we should do about this ?

We should request users only once. If, like in this situation we didn't get info about some user, we can show `Unknown` as you do now. Note, that you can check how we do on Project Listing page. After loading the list of projects, we request all the users once. If we cannot get some, we don't show them or show `unknown`.
So your approach is good, just have to request users one time only.

**Comment by jankyzhang** [comment]
@maxceem ,
I just update the code.
Please check it.
Thanks.

**Pull request merged**
