### PR TITLE
Issue #1534 - Update the user tooltip with a unified component in all instances

### PR DESCRIPTION
**Pull request by maxceem**
In this commit to connect app only take care about adding Tooltip to every required place.
Changes to Tooltip by itself are done in [PR](https://github.com/appirio-tech/react-components/pull/281) to react-components repository.

### CODE REVIEW

**Comment by vic-topcoder** [comment]
We should add this after we merge the SVG icons. There are breaking changes in the components due to the new way we include SVG elements. I also saw some positioning/sizing issues. @maxceem can you resolve the issues on your side and take latest from DEV, I think we merged the SVG refactoring code there.

**Comment by maxceem** [comment]
The latest changes from the `dev` branch are merged.
I've added tooltips to post comments avatars, I've missed previously.
Note, that without updating `appitio-tech-react-compontents` where I've updated tooltip component, tooltips arrows are displayed without borders.

### Possible issues
There are some new warnings/errors in browser console which are not connected with my changes.
- When clicking some project on the project list page and we go to the project dashboard:
   ```
   warning.js:33 Warning: setState(...): Can only update a mounted or mounting component. This usually means you called setState() on an unmounted component. This is a no-op. Please check the code for the ProjectListTimeSortColHeader component.
   ```
- On the project dashboard page:
   ```
   Helpers.js:301 Uncaught (in promise) TypeError: defaultScroller.register is not a function
   ```

**Comment by vic-topcoder** [comment]
@gondzo Do we have the changes needed in https://github.com/appirio-tech/tc-ui?

**Comment by gondzo** [comment]
you mean in https://github.com/appirio-tech/react-components ?
Yes, it's merged

**Pull request merged**
