### PR TITLE
fix: issue-4301

### PR DESCRIPTION
**Pull request by yoution**

### CODE REVIEW

**Comment by yoution** [comment]
for issue #4301

**Review by maxceem — CHANGES_REQUESTED** [review]
@yoution Approach looks great. But I guess how Ariel wants it to work is, when we click outside it should work the same as if we press `Enter` or `Space`. I. e. the value should be created not only keep text:

image

**Comment by yoution** [comment]
@maxceem how about this approach 
https://monosnap.com/file/P0kV6LXfKtdlzh4PI9JE6AHwvbZVjb

**Review by maxceem — CHANGES_REQUESTED** [review]
@yoution this is very close to what we need.

The only one thing, when we click outside can we add an option which we enter into the field, not what is chose in the list?

image

The logic is, if we want to select an option, we have to click the option. But if we click outside, we want to select what we enter into the field, not the option.

**Review by maxceem — APPROVED** [review]
Works great now @yoution!

**Pull request merged**
