### PR TITLE
fix #2769 - [Metadata management] JSON is cleared when there is a syn…

### LINKED ISSUE #2769: [$50] [Metadata management] JSON is cleared when there is a syntax error
### Expected behavior
Current JSON should stay.

### Actual behavior
Current JSON is replaced with `{}` empty object.

### Steps to reproduce the problem (scenario 1)
- Go to project templates list https://connect.topcoder-dev.com/metadata/projectTemplates
- Select any template and click Maximize to edit the template JSON
- Make a syntax mistake, for example, add a comma after some value
- Select another browser tab, and after coming back to the tab with JSON. JSON will be empty

See screencast https://monosnap.com/file/hrscvjoxVMUJbPKQjVIjtalH1P4TYf

### Steps to reproduce the problem (scenario 2)
- Go to project templates list https://connect.topcoder-dev.com/metadata/projectTemplates
- Select any template and click Maximize to edit the template JSON
- Copy all the JSON to your text editor
- In your text editor make some syntax mistake in the JSON
- Copy the JSON from your text editor with the syntax mistake and paste to the JSON editor on Connect App
- Instead of pasting your JSON with a syntax error, it will become empty

See screencast https://monosnap.com/file/8xTAFe9zM3iK7mnKKZcC2t9wjVLjqQ

fyi @vikasrohit @RishiRajSahu

### PR DESCRIPTION
**Pull request by vigneshTheDev**
fix #2769  [Metadata management] JSON is cleared when there is a syntax error

### CODE REVIEW

**Comment by vigneshTheDev** [comment]
@maxceem, when there is an error in json, it's not able to parse. Obviously, the library is not able to format. After you pasted the json with error, fix the error and the json is automatically formatted back. 

Let me see if there's any workaround to keep the original formatting though.

**Comment by vigneshTheDev** [comment]
Hi @maxceem, I couldn't find a workaround on this. Though I found the root cause from the JSON editor library: https://github.com/AndrewRedican/react-json-editor-ajrm/blob/b7b261d469f06da2399355b1eebaced0eaa0e72c/src/index.js#L571

here is a minimal reproduction code: http://jsfiddle.net/HBEzc/
insertHtml command is the culprit. it trims off the whitespaces.

Please feel free to release the issue for others.

Otherwise, if you would like to accept this fix for a reduced prize and create another issue for the formatting issue, It's fair with me.

**Comment by maxceem** [comment]
@vigneshTheDev Thank you for details. I'll check it and will come back to you shortly.

**Comment by maxceem** [comment]
@vigneshTheDev to keep you updated. I'm discussing this issue with the team, most likely will get a response on Monday.

**Comment by vigneshTheDev** [comment]
Thanks for the update @maxceem :)

**Comment by vigneshTheDev** [comment]
Hi @maxceem, Yes that's totally fair. 
Also, thanks for sharing additional info :)

**Pull request merged**
