### PR TITLE
fix: #4236

### PR DESCRIPTION
**Pull request by yoution**
@maxceem please review for #4236

### CODE REVIEW

**Review by maxceem — CHANGES_REQUESTED** [review]
@yoution great fix.

There is only one thing to improve. When I update project status using admin user (maybe other too), additional data which we load for some members got lost. See demo video https://monosnap.com/file/f8Z2U9EVbZasx8oTcY5wcBuZlX5i8p.

I think it happens because after loading project list, we additionally load some user details and put it inside project data in Redux store.

So we have to 2 way so go:
- after updating project reload user data for it.
- or when we update project we can get `members` from the previous project data, and apply it to the updated project data, so we don't have to reload members.

Maybe you have another idea.

**Comment by yoution** [comment]
@maxceem please review again

**Comment by maxceem** [comment]
Thanks for the update, @yoution. Would it be hard to update the project object as it was done before and just keep members?

I like the previous way as it was more universal, if tomorrow we update something else from this page. Also, last updated time is updating during status update and the user who did the last update. So it would be nice if all these data got updated.

**Comment by yoution** [comment]
@maxceem I know ,I will update soon

**Comment by yoution** [comment]
@maxceem please review again again

**Review by maxceem — APPROVED** [review]
Thanks, @yoution, works perfectly.

**Pull request merged**
